version: '3.8'

services:

  db:
    container_name: pg_air
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_air
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres_air.dump:/postgres_air.dump
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
 