version: '3.9'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  postgres:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: omdb
    ports:
      - "5432:5432"
    volumes: 
      - ./omdb.dump:/omdb.dump
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://root:root@postgres:5432/omdb?sslmode=disable"
    links:
      - postgres
      - prometheus