version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres:15.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: omdb
    ports:
      - "5432:5432"
    volumes: 
      - ./omdb.dump:/omdb.dump
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.21
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"